[package]
name = "server-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
# Project sub-modules
common-audit-log = { workspace = true }
server-utils = { workspace = true }
server-types = { workspace = true }
# Config libs
config = { workspace = true }
dotenv = "0.15.0"
# Lang libs
regex = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, default-features = false, features = ["v4"] }
thiserror = { workspace = true }
anyhow = { workspace = true }
arc-swap = { workspace = true }
once_cell = { workspace = true }
sysinfo = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
snafu = { workspace = true }
strum = { workspace = true, features = ["derive"] }
mimalloc = { workspace = true, default-features = false }
local-ip-address = { workspace = true }
# Command line libs
clap = { workspace = true }
# Serialization libs
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
validator = { workspace = true, features = ["derive"] }
# Logger libs
env_logger = { workspace = true }
log = { workspace = true }
# Prometheus libs
lazy_static = { workspace = true }
prometheus = { workspace = true }
axum-prometheus = { workspace = true }
# Tracing libs
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json", "env-filter"] }
tracing-opentelemetry = { workspace = true }
tracing-futures = { workspace = true }
tracing-attributes = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic"] }
opentelemetry-http = { workspace = true }
# Async core libs
tokio = { workspace = true, features = ["full", "tracing"] }
async-trait = { workspace = true }
# Web HTTP libs
axum = { workspace = true }
hyper = { workspace = true, features = ["full"] }
tower = { workspace = true }
tower-http = { workspace = true, features = ["trace", "auth"] }
tower-cookies = { workspace = true }
globset = { workspace = true }
rust-embed = { workspace = true }
mime_guess = { workspace = true }
# Database libs
mongodb = { workspace = true }
futures = { workspace = true }
sqlx = { workspace = true, features = [
    "runtime-tokio-rustls",
    "sqlite",
    "macros",
    "chrono"
] }
idb = { workspace = true }
serde-wasm-bindgen = { workspace = true }
wasm-bindgen = { workspace = true }
# Swagger libs
utoipa = { workspace = true, features = ["axum_extras"] }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }
mac_address = { workspace = true }
# Auth libs
reqwest = { workspace = true, features = ["json"] }
url = { workspace = true }
oauth2 = { workspace = true }
openidconnect = { workspace = true }
jsonwebtoken = { workspace = true }
# Encrypt libs
openssl = { workspace = true }
rsa = { workspace = true }
sha2 = { workspace = true }
# Cache libs
moka = { workspace = true, features = ["future"] }
redis = { workspace = true, features = ["tokio-comp", "cluster-async"] }
# Ethers libs
ethers = { workspace = true, features = ["abigen", "ws", "rustls"] }
eyre = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "bench_main"
harness = false

[build-dependencies]
chrono = { workspace = true, default-features = false, features = ["clock"] }
