[package]
name = "benchmarks"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
indicatif = "0.17.1"
clap.workspace = true
tokio.workspace = true
