[package]
name = "benchmarks"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
criterion = "0.5.1"
regex.workspace = true
globset.workspace = true
