# SPDX-License-Identifier: GNU GENERAL PUBLIC LICENSE Version 3
#
# Copyleft (c) 2024 James Wong. This file is part of James Wong.
# is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# James Wong is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with James Wong.  If not, see <https://www.gnu.org/licenses/>.
#
# IMPORTANT: Any software that fully or partially contains or uses materials
# covered by this license must also be released under the GNU GPL license.
# This includes modifications and derived works.
#
[workspace]
members = [
    "benchmarks",
    "src/common/audit-log",
    "src/common/macro",
    "src/common/makestruct",
    "src/common/mem-prof",
    "src/common/telemetry",
    "src/cmd",
    "src/core",
    "src/types",
    "src/utils",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["James Wong"]
description = "Generic Web Note Server of Personal."
documentation = "https://github.com/wl4g/my-webnote"
license = "GPL-3.0"

[workspace.lints]
clippy.print_stdout = "warn"
clippy.print_stderr = "warn"
clippy.implicit_clone = "warn"
rust.unknown_lints = "deny"

[workspace.dependencies]
# workspaces members
common-audit-log = { path = "src/common/audit-log" }
common-error = { path = "src/common/error" }
common-macro = { path = "src/common/macro" }
common-makestruct = { path = "src/common/makestruct" }
common-mem-prof = { path = "src/common/mem-prof" }
common-telemetry = { path = "src/common/telemetry" }
server-cmd = { path = "src/cmd" }
server-core = { path = "src/core" }
server-types = { path = "src/types" }
server-utils = { path = "src/utils" }
# Lang libs
regex = "1.10.3"
chrono = "0.4.40"
uuid = "1.9.1"
thiserror = "1.0.61"
anyhow = "1.0.86"
arc-swap = "1.7.1"
once_cell = "1.19.0"
sysinfo = "0.29.11"
base64 = "0.22.1"
hex = "0.4.3"
snafu = "0.8.5"
strum = "0.25"
mimalloc = "0.1.43"
local-ip-address = "0.6.1"
# Config libs
config = "0.14.0"
dotenv = "0.15.0"
# Command line libs
clap = "4.5.7"
# Serialization libs
serde = "1.0.197"
serde_json = "1.0.64"
serde_yaml = "0.9.32"
validator = "0.18.1"
# Logger libs
env_logger = "0.11.3"
log = "0.4.22"
# Prometheus libs
lazy_static = "1.4.0"
prometheus = "0.13.4"
axum-prometheus = "0.6.1"
# Tracing libs
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-opentelemetry = "0.24.0"
tracing-futures = "0.2"
tracing-attributes = "0.1.26"
opentelemetry = "0.23.0"
opentelemetry_sdk = "0.23.0"
opentelemetry-otlp = "0.16.0"
opentelemetry-http = "0.12.0"
# Async core libs
tokio = "1.38.0"
async-trait = "0.1.81"
# Web HTTP libs
axum = "0.7.5"
hyper = "1.3.1"
tower = "0.4.1"
tower-http = "0.5.2"
tower-cookies = "0.10.0"
globset = "0.4.14"
rust-embed = "8.5.0"
mime_guess = "2.0.4"
# Database libs
mongodb = "3.0.1"
futures = "0.3"
sqlx = "0.7.4"
idb = "0.6.4"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.93"
# Swagger libs
utoipa = "4.2.3"
utoipa-swagger-ui = "7.1.0"
mac_address = "1.1.7"
# Auth libs
reqwest = "0.12.5"
url = "2.3"
oauth2 = "4.3"
openidconnect = "3.5.0"
jsonwebtoken = "9.3.0"
# Encrypt libs
openssl = "0.10.64"
rsa = "0.9.6"
sha2 = "0.10.8"
# Cache libs
moka = "0.12.8"
redis = "0.25.4"
# Ethers libs
ethers = "2.0.14"
eyre = "0.6.12"
# Build dependencies
criterion = "0.4"
